Restructure library into record and batch
gadomski/pyisd pull request #36
Opened 2023-12-22 16:32 UTC by gutzbenj

2023-12-27 12:37 UTC, gadomski requested changes
The change from a src layout to a flat layout shouldn't be required to implement the changes as described in the PR description. Please separate out the src-to-flat change from the rest of the changes, so we can assess them independently. Thanks!

2023-12-27 14:31 UTC, gutzbenj commented
Dear @gadomski ,

I have undone the moving of the code - I did this because I had problems simply running the tests!

2023-12-27 17:13 UTC, gadomski commented
> I have undone the moving of the code

Thank you!

> I had problems running the tests!

If there's any changes needed to https://github.com/gadomski/pyisd/#development, PRs are welcome!

2023-12-27 17:36 UTC, gadomski requested changes
In addition to the in-line change requests, can you keep the `isd.io` module? Sometimes reading the entire ISD file into memory all at once (as is done w/ the `Batch` class) may be undesirable.

2023-12-27 17:36 UTC, gadomski commented on README.md
> +from src.isd import Batch
```suggestion
from isd import Batch
```

The README instruction should assume that the `isd` library is available in the local environment, usually via `pip install -e .` or `pip install isd`.

2023-12-27 17:36 UTC, gadomski commented on src/isd/record.py
> +        return self.to_dict() == other.to_dict()
This is one example of non-essential changes grouped together into a single pull request. If possible, I'd prefer this pull request be stripped down to only the changes needed to add `Batch`, and add `__eq__` methods (etc) in another pull request so we can assess them separately.

2023-12-27 17:36 UTC, gadomski commented on src/isd/record.py
> +    def from_string(cls, string: Union[str, BytesIO]) -> "Record":
Can you provide some rationale behind the name change?

2023-12-27 17:36 UTC, gadomski commented on src/isd/record.py
> +    def from_string(cls, string: Union[str, BytesIO]) -> "Record":
By changing `line` to `string`, you create a good bit of noise in the diff where it might not be necessary? Unless there's a compelling reason to change the argument name, I'd prefer to keep it the same.

2023-12-27 17:36 UTC, gadomski commented on src/isd/record.py
> +            return None, message
What's the rationale behind making this a class method? It doesn't appear that `cls` is used anywhere in the method.

2023-12-27 17:36 UTC, gadomski commented on tests/conftest.py
> +def batch(uncompressed_path) -> Batch:
Please type the argument here.

2023-12-27 17:36 UTC, gadomski commented on tests/test_batch.py
> +    # filter by start_date
This comment (and the ones below) are unnecessary IMO, it's clear to me what's happening from the name of the function and argument names.

2023-12-27 17:39 UTC, gutzbenj commented
- [ ] I'd hand in a PR that moves the code from `src/isd` to `isd`, as at the moment the imports in the tests are automatically pointing to the installed isd library - I installed isd into my local environment - and are not overwritten by the local git path (because of it differing by the `src/` prefix). It may also be just enough to import from `src/isd` inside the tests folder but moving the actual src folder to the root is also the default behavior.

2023-12-27 17:40 UTC, gadomski commented
> I'd hand in a PR that moves the code from src/isd to isd, as at the moment the imports in the tests are automatically pointing to the installed isd library - I installed isd into my local environment - and are not overwritten by the local git path (because of it differing by the src/ prefix). It may also be just enough to import from src/isd inside the tests folder but moving the actual src folder to the root is also the default behavior.

Are you installing in editable mode, e.g. `pip install -e .`?

2023-12-28 11:02 UTC, gutzbenj commented on src/isd/record.py
> +            return None, message
Sorry, this was not intended! It should be a staticmethod instead. Fixed it.

2023-12-28 11:02 UTC, gutzbenj commented on src/isd/record.py
> +        return self.to_dict() == other.to_dict()
Dropped it again, as also dataclass already comes with an sufficient `__eq__` method.

2023-12-28 11:03 UTC, gutzbenj commented on README.md
> +from src.isd import Batch
Installing the library in editable mode makes the tests pass :)

2023-12-28 11:09 UTC, gutzbenj commented on src/isd/record.py
> +    def from_string(cls, string: Union[str, BytesIO]) -> "Record":
I renamed the method to align with the method of the `Batch` class. It seemed to me more clear having multiple `from_` methods (with the new possibility to create from a file/path) that create the instance from different types of data e.g. path, string,... .

2023-12-28 11:14 UTC, gutzbenj commented on src/isd/record.py
> +    def from_string(cls, string: Union[str, BytesIO]) -> "Record":
I thought `string` would be a better abstraction then line - what really makes a line a line? - and it would allow us to have almost the same function signature as in the `Record` class. Do you generally agree on this? I could separate it as well and make another PR.

2023-12-28 12:01 UTC, gutzbenj commented
Dear @gadomski ,
I pushed again and did the adjustments you suggested.

I didn't yet revert the renaming of `from_string` waiting for your answer on that topic.

2024-01-17 13:46 UTC, gadomski requested changes

2024-01-17 13:46 UTC, gadomski commented on CHANGELOG.md
> +- Restructure library into record and batch
```suggestion
- Restructure library into record and batch ([#36](https://github.com/gadomski/pyisd/pull/36))
```

2024-01-17 13:46 UTC, gadomski commented on src/isd/batch.py
> +import pandas as pd
My personal style preference is to _not_ abbreviate package/module names.

```suggestion
import datetime

from isd.record import Record

import pandas
```

2024-01-17 13:46 UTC, gadomski commented on src/isd/batch.py
> +import gzip
This allows return types w/o the quote marks below.

```suggestion
from future import __annotations__
import gzip
```

2024-01-17 13:46 UTC, gadomski commented on src/isd/batch.py
> +    def parse(cls, lines: Union[str, BytesIO]) -> "Batch":
Enabled by the `from future import __annotations__`. Needs to be applied to `from_path` and `filter_by_datetime` as well.

```suggestion
    def parse(cls, lines: Union[str, BytesIO]) -> Batch:
```

2024-01-17 13:46 UTC, gadomski commented on src/isd/batch.py
> +        """Returns an iterator over records filtered by start and end datetimes (both optional)."""
```suggestion
        """Returns a new Batch with records filtered by start and end datetimes (both optional)."""
```

2024-01-17 13:46 UTC, gadomski commented on src/isd/batch.py
> +    def to_df(self) -> pd.DataFrame:
My personal style preference is to not use abbreviations.

```suggestion
    def to_data_frame(self) -> pd.DataFrame:
```

2024-01-17 13:46 UTC, gadomski commented on src/isd/cli.py
> +        record_ = batch[index]
Why is the trailing `_` necessary?

2024-01-17 13:46 UTC, gadomski commented on src/isd/io.py
> -            yield Record.parse(line)
What's the rationale behind removing this free function?

2024-01-17 13:46 UTC, gadomski commented on src/isd/record.py
> +    def timestamp(self) -> datetime.datetime:
What's the rationale behind changing this name? It returns a `datetime`, so `datetime` seems like a reasonable-enough name.

2024-01-17 13:46 UTC, gadomski commented on src/isd/record.py
> +    def optional(
This wasn't "private" before, but probably should be.

```suggestion
    def _optional(
```

2024-01-17 13:46 UTC, gadomski commented on tests/test_io.py
> -        assert len(records) == 500
Shouldn't be removed if we keep `isd.io.from_text_io`.

2024-01-17 19:27 UTC, gutzbenj commented on src/isd/cli.py
> +        record_ = batch[index]
Because it would otherwise have the same name as the click function itself. Would you prefer to name the variable differently?

2024-01-17 19:33 UTC, gutzbenj commented on src/isd/io.py
> -            yield Record.parse(line)
I believe that this function - after implementing the Batch class - is dispensable. See, having the entire file already in memory - as TextIO - it most probably makes more sense to just read the entire text into a Batch and iterate through the batch records. Would you agree on that? Except for the test of that function, it is not shown in any usecase/example, so it is questionable that it is used at all.

2024-01-17 19:33 UTC, gutzbenj commented on src/isd/record.py
> +    def timestamp(self) -> datetime.datetime:
Will rvert this as well.

2024-01-27 23:32 UTC, gutzbenj commented
Dear @gadomski ,

could you please review the open points?

2024-02-02 13:24 UTC, gadomski approved these changes

2024-02-02 13:25 UTC, merged

2024-02-02 13:25 UTC, gadomski commented
Thanks for the contribution, and apologies for the long turnaround!

2024-02-02 14:43 UTC, gutzbenj commented
Was just on a walk and thought about the PR 😁. Many thanks, will hand in more PRs asap.