Make pandas optional
gadomski/pyisd pull request #43
Opened 2024-02-02 16:41 UTC by gutzbenj

2024-02-09 13:04 UTC, gadomski requested changes

2024-02-09 13:04 UTC, gadomski commented on src/isd/batch.py
> +    def to_data_frame(self) -> "pandas.DataFrame":
We can use a

```python
from future import __annotations__
```

to avoid these quotes, I think.

2024-02-09 13:04 UTC, gadomski commented on src/isd/batch.py
> +        import pandas
```suggestion
        try:
            import pandas
        except ImportError as err:
            message = "The `pandas` optional dependency is required to use `to_data_frame`. Install this dependency with `pip install 'isd[pandas]'`.
            raise ImportError("{}\n{}", message, err)
```

That might not be exactly correct, but you get the gist.

2024-02-11 16:52 UTC, gutzbenj commented
Dear @gadomski ,

please re-review :)

2024-03-05 14:56 UTC, gadomski requested changes
@gutzbenj I can't push to your branch, but can you take up the changes in b117e40154611aa64c66d11a4eb9cc570aa27f43? Rather than use PR suggestions, I just made some edits. Mostly removing the **pytest** mark b/c I don't think it's necessary, and some spurious whitespace changes as well. Thanks!

2024-03-14 15:43 UTC, gadomski commented
> I'm really confused now, please clear my worries 😵‍💫

Yeah, I apologize @gutzbenj, thanks for your patience. I only come back to this project every once in a while and sometimes I forget previous decisions I've made 🙃 . To avoid further confusion, I've rolled up both of these PRs with my current way of thinking into https://github.com/gadomski/pyisd/pull/47. Thanks for your contribution!

2024-03-14 15:44 UTC, closed without merging